
server:
  port: 8081

# SPRING ----------------------------------------------------------------------------------------------------
spring:
  application:
    name: shopping-mall
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Mail ---------------------------------------------------------------------------------------------------
  mail:
    host: smtp.gmail.com
    port: 587
    username: #
    password: #
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  # DATASOURCE ----------------------------------------------------------------------------------------------------
  datasource:
    url: jdbc:mysql://localhost:3307/grooo_shopping_mall_backend?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA ----------------------------------------------------------------------------------------------------
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  messages:
    basename: messages
    use-code-as-default-message: true
  #mail


application:
  swagger:
    base-url: localhost:8081
  jwt:
    confirmation-secret: secret1610
    time-to-live: 3600 # seconds

